name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main  # O branch onde o workflow será acionado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build # Comando para construir seu site, caso use um bundler ou framework (opcional)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Pasta onde seus arquivos estão localizados após o build, pode ser "public", "build" ou outra
